[package]
name = "db-cloner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.9"
dotenvy = "0.15"
mysql_async = "0.32"
tokio = { version = "1.29", features = ["full"] }
